ignore_unreachable_actions:
- action_mailbox/ingresses/mandrill/inbound_emails#health_check
- active_storage/representations/proxy#send_stream
- active_storage/blobs/proxy#send_stream
- devise#_prefixes
- devise/omniauth_callbacks#failure
- devise/omniauth_callbacks#passthru
- devise/unlocks#create
- devise/unlocks#show
- devise/unlocks#new
- devise/confirmations#create
- devise/confirmations#new
- devise/confirmations#show
- application#authenticate_admin!
- home#authenticate_admin!
- devise#authenticate_admin!
- devise/omniauth_callbacks#authenticate_admin!
- devise/passwords#authenticate_admin!
- devise/sessions#authenticate_admin!
- devise/unlocks#authenticate_admin!
- devise/confirmations#authenticate_admin!
- devise/registrations#authenticate_admin!
- app_tools/mains#authenticate_admin!
- app_tools/styles#authenticate_admin!

ignore_unused_routes:
- rails/conductor/action_mailbox/inbound_emails#edit
- rails/conductor/action_mailbox/inbound_emails#update
- rails/conductor/action_mailbox/inbound_emails#update
- rails/conductor/action_mailbox/inbound_emails#destroy
- devise/confirmations#new
- devise/confirmations#show
- devise/confirmations#create
- devise/unlocks#new
- devise/unlocks#show
- devise/unlocks#create
- health_check

ignore_uninitialized_constant:
- TestProf

